USE [master]
GO 

/****** Object:  Database [CodingChallenge_WebForms]    Script Date: 3/1/2020 7:40:41 PM ******/
CREATE DATABASE [CodingChallenge_WebForms]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CodingChallenge_WebForms', FILENAME = N'C:\Users\chris\CodingChallenge_WebForms.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CodingChallenge_WebForms_log', FILENAME = N'C:\Users\chris\CodingChallenge_WebForms_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [CodingChallenge_WebForms] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CodingChallenge_WebForms].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CodingChallenge_WebForms] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CodingChallenge_WebForms] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CodingChallenge_WebForms] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CodingChallenge_WebForms] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CodingChallenge_WebForms] SET ARITHABORT OFF 
GO

ALTER DATABASE [CodingChallenge_WebForms] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CodingChallenge_WebForms] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CodingChallenge_WebForms] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CodingChallenge_WebForms] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CodingChallenge_WebForms] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CodingChallenge_WebForms] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CodingChallenge_WebForms] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CodingChallenge_WebForms] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CodingChallenge_WebForms] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CodingChallenge_WebForms] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CodingChallenge_WebForms] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CodingChallenge_WebForms] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CodingChallenge_WebForms] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CodingChallenge_WebForms] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CodingChallenge_WebForms] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CodingChallenge_WebForms] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CodingChallenge_WebForms] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CodingChallenge_WebForms] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CodingChallenge_WebForms] SET  MULTI_USER 
GO

ALTER DATABASE [CodingChallenge_WebForms] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CodingChallenge_WebForms] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CodingChallenge_WebForms] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CodingChallenge_WebForms] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CodingChallenge_WebForms] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CodingChallenge_WebForms] SET QUERY_STORE = OFF
GO

USE [CodingChallenge_WebForms]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [CodingChallenge_WebForms] SET  READ_WRITE 
GO


